### ISSUE TITLE
d02_defconfig warning

### ISSUE THREAD

**Issue by glevand** [open-estuary/kernel#2]
Got this warning with 'make d02_defconfig':

```
arch/arm64/configs/d02_defconfig:1159:warning: override: reassigning to symbol CAN
```

**Comment by shamiali2008** [comment]
Thanks for reporting this. This is corrected in master now.

**Comment by glevand** [comment]
Seems OK.  Fixed in https://github.com/open-estuary/kernel/commit/6fd84652080c40b42b1beb3edaaacd06fb1f2a5b.
